# -*- coding: utf-8 -*-
"""comfyui

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Xw6qKOcl10meVLbosInbNzRYj59xqtp

# 🛠️ Instalação e Setup
"""

# Commented out IPython magic to ensure Python compatibility.
# 1. Instalar o ComfyUI
!git clone https://github.com/comfyanonymous/ComfyUI
# %cd ComfyUI
!pip install -r requirements.txt

# 2. Instalar o Gerenciador (Manager) - Essencial para você baixar o Impact Pack depois
# %cd custom_nodes
!git clone https://github.com/ltdrdata/ComfyUI-Manager
# %cd ..

# 3. Criar o Túnel para você conseguir abrir a interface
!pip install pyngrok

"""# 🛠️ Setup e Modelos"""

# Commented out IPython magic to ensure Python compatibility.
# Célula 2 (Versão Sem Senha): Baixar Modelos
# %cd /content/ComfyUI/models/checkpoints/
# Juggernaut XL v9 via link direto estável
!wget -c https://civitai.com/api/download/models/348913?type=Model&format=SafeTensor -O Juggernaut-XL-v9.safetensors

# %cd /content/ComfyUI/models/ipadapter/
# IPAdapter Plus SDXL
!wget -c https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter-plus_sdxl_vit-h.bin

# %cd /content/ComfyUI/models/ultralytics/bbox/
# Detector de Rosto (Link alternativo direto)
!wget -c https://github.com/BubblyPop/ComfyUI-Nodes/raw/main/models/face_yolov8n.pt

# %cd /content/ComfyUI
print("✅ Agora sim, modelos baixados sem erro de senha!")

"""# 📂 Logar no Google Drive"""

# 1. Montar o Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 2. Criar as pastas no Drive se não existirem
import os
os.makedirs('/content/drive/MyDrive/ComfyUI_Cloud/checkpoints', exist_ok=True)
os.makedirs('/content/drive/MyDrive/ComfyUI_Cloud/ipadapter', exist_ok=True)
os.makedirs('/content/drive/MyDrive/ComfyUI_Cloud/clip_vision', exist_ok=True)
os.makedirs('/content/drive/MyDrive/ComfyUI_Cloud/ultralytics', exist_ok=True)

# 3. Baixar os modelos DIRETO para o seu Google Drive (Só precisa fazer UMA VEZ na vida)
# Juggernaut XL
if not os.path.exists('/content/drive/MyDrive/ComfyUI_Cloud/checkpoints/Juggernaut-XL-v9.safetensors'):
    print("Baixando Juggernaut para o Drive...")
    !wget -c https://civitai.com/api/download/models/348913?type=Model&format=SafeTensor -O /content/drive/MyDrive/ComfyUI_Cloud/checkpoints/Juggernaut-XL-v9.safetensors

# Detector de Rosto (O .pt que você precisa)
if not os.path.exists('/content/drive/MyDrive/ComfyUI_Cloud/ultralytics/face_yolov8n.pt'):
    print("Baixando Detector de Rosto para o Drive...")
    !wget -c https://github.com/BubblyPop/ComfyUI-Nodes/raw/main/models/face_yolov8n.pt -O /content/drive/MyDrive/ComfyUI_Cloud/ultralytics/face_yolov8n.pt

# 4. Criar links simbólicos (Isso faz o ComfyUI ler do Drive instantaneamente)
!ln -s /content/drive/MyDrive/ComfyUI_Cloud/checkpoints/* /content/ComfyUI/models/checkpoints/
!ln -s /content/drive/MyDrive/ComfyUI_Cloud/ultralytics/* /content/ComfyUI/models/ultralytics/bbox/

print("✅ Drive conectado e modelos vinculados!")

"""# 🚀 Abrir o Túnel e Ligar ComfyUI"""

# Commented out IPython magic to ensure Python compatibility.
# 1. Entra na pasta e limpa o que estiver travado
# %cd /content/ComfyUI
!pkill -f main.py
!pkill cloudflared

# 2. Roda o ComfyUI em SEGUNDO PLANO (Background)
# O "> /dev/null 2>&1 &" serve para não poluir sua tela e liberar a célula
print("🚀 Ligando o ComfyUI no 'escuro'...")
!python main.py --dont-print-server > /dev/null 2>&1 &

# 3. Espera o servidor "acordar"
import time
time.sleep(15)

# 4. Roda o Cloudflare na mesma célula
print("🔗 Gerando o link do túnel...")
!wget -q -nc https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb > /dev/null 2>&1
!cloudflared tunnel --url http://127.0.0.1:8188